export const topics = [
  "Science Fiction",
  "Gothic Fiction",
  "Horror",
  "Monsters",
  "Tragedy",
  "Romance",
  "Adventure",
  "Autobiographical Fiction",
  "Bildungsroman",
  "Historical Fiction",
  "Psychological Fiction",
  "Domestic Fiction",
  "Drama",
  "Fantasy",
  "Epic Poetry",
  "Political Satire",
  "Classical Literature",
  "Romantic Fiction",
  "Young Adult Fiction",
  "Pastoral Fiction",
  "Supernatural Fiction",
  "Feminist Fiction",
  "Social Class Fiction",
  "Historical Romance",
];
